### ISSUE TITLE
Image missing in Activity section of Session-01

### ISSUE THREAD

**Issue by moingshaikh** [gideonthomas/offline-icebreakers#1]
Hi there,

An image (alt tagged as "An image of two activity participants talkign about their vocabulary cards") is missing under the "Introduce the Activity" paragraph of "Activity" section of first activity (Sessiopn01 - Web Mechanics Speed Dating). The broken image path is: https://googledrive.com/host/0B5ga06pZVp55VXJ5RlhhOVRuS3M/MOTW_06

Screenshot:

![img missing](https://cloud.githubusercontent.com/assets/7282553/20439975/09fcbf92-ade4-11e6-845a-5d41572c51af.png)

**Comment by maykonchagas** [comment]
I've found the ref to the image name pointing to this URL: https://juliahivenyc.makes.org/thimble/MTgwOTQ0ODk2/web-mechanics-speed-dating_ from Julia Vallera, but it's missing too.

**Comment by moingshaikh** [comment]
Yes, that's one missing too. Hopefully, @gideonthomas or Julia would fix it.

**Comment by gideonthomas** [comment]
Hey @chadsansing, would you be able to update the image in the Web Speed Dating activity for Offline Icebreakers? I'll update it in the copies that are being used for localization after that.

@moinshaikh and @mchagas, I will let you know as soon as they are updated. I apologize for the issue but thank you for reporting it.

**Comment by chadsansing** [comment]
@gideonthomas - I added a new one from our Cleveland IMLS training to the version on /activities.

**Comment by gideonthomas** [comment]
@chadsansing can you link the page with the correct image on it? It still shows up as broken for me.

**Comment by chadsansing** [comment]
Oops - forgot my PR. Should be good now - https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session01-web-mechanics-speed-dating.html#step-2.

**Comment by gideonthomas** [comment]
Perfect! Much appreciated @chadsansing

**Comment by gideonthomas** [comment]
@mchagas and @moinshaikh, the github page should now be updated with the latest image.

Feel free to reach out to me if you have any questions!

**Comment by moingshaikh** [comment]
Thanks Gideon!
